apiVersion: v1
kind: PersistentVolume
metadata:
  name: jaydipsinh-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  gcePersistentDisk:
    pdName: disk-1
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jaydipsinh-pvc
spec:
  volumeName: jaydipsinh-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service2-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service2
  template:
    metadata:
      labels:
        app: service2
    spec:
      containers:
      - name: service2
        image:  us-central1-docker.pkg.dev/csci-5409-term-project/k8s/k8s-service2:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        volumeMounts:
        - mountPath: /app/Jaydipsinh_PV_dir
          name: storage
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: jaydipsinh-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: service2
spec:
  selector:
    app: service2
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000 